export const metaData = {
  title: {
    template: `%s | ${process.env.TEMPLATE}`,
    default: process.env.TITLE,
  },
  description: process.env.DESCRIPTION,
  alternates: {
    canonical: process.env.NEXT_PUBLIC_URL_CLI,
    languages: {
      "ko-KR": "/ko-KR",
      "en-US": "/en-US",
    },
  },
  openGraph: {
    title: process.env.TITLE,
    description: process.env.DESCRIPTION,
    url: process.env.NEXT_PUBLIC_URL_CLI,
    siteName: process.env.SITENAME,
    images: [
      {
        url: process.env.LOGO_URL,
        width: 800,
        height: 600,
        alt: `${process.env.TITLE} logo image`,
      },
      {
        url: process.env.LOGO_URL,
        width: 1800,
        height: 1600,
        alt: `${process.env.TITLE} logo image`,
      },
    ],
    locale: ["en-US", "ko-KR"],
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  twitter: {
    card: "summary_large_image",
    title: process.env.TITLE,
    description: process.env.DESCRIPTION,
    images: [process.env.LOGO_URL],
  },
  generator: "Next.js",
  applicationName: "Next.js",
  referrer: "origin-when-cross-origin",
  keywords: [
    "커뮤니티",
    "유머",
    "일상",
    "투자",
    "스포츠",
    "연예",
    "물물교환",
    "중고거래",
    "clipmk",
    "clip",
    "클립마켓",
  ],
  authors: [{ name: "WJJ" }, { name: "MHU" }],
  creator: "WJJ & MHU",
  publisher: "WJJ & MHU",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  other: {
    "google-site-verification": "g2QNUQioOSVhibeq1m4sAntQTiBwJtFRgnUD-rlmfQo",
  },
};
